#!/bin/bash

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Find BATTLESTAG-BOT root by going up from script location
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BIN_DIR="$REPO_ROOT/bin"
CONFIG_DIR="${HOME}/.config/agent-gateway"

echo "=== Agent Gateway Installation ===="
echo ""

# Create bin directory if it doesn't exist
if [ ! -d "$BIN_DIR" ]; then
    echo "Creating bin directory: $BIN_DIR"
    mkdir -p "$BIN_DIR"
fi

# Create config directory if it doesn't exist
if [ ! -d "$CONFIG_DIR" ]; then
    echo "Creating config directory: $CONFIG_DIR"
    mkdir -p "$CONFIG_DIR"
fi

# Config setup function
setup_config() {
    echo ""
    echo "=== Configuration Setup ==="
    echo ""

    # Load existing config values if available
    local CURRENT_OLLAMA_URL=""
    local CURRENT_OLLAMA_MODEL=""
    local CURRENT_PORT=""

    if [ -f "$CONFIG_DIR/config.yaml" ]; then
        CURRENT_OLLAMA_URL=$(grep -A1 "^ollama:" "$CONFIG_DIR/config.yaml" | grep "url:" | awk '{print $2}' || echo "")
        CURRENT_OLLAMA_MODEL=$(grep -A2 "^ollama:" "$CONFIG_DIR/config.yaml" | grep "model:" | awk '{print $2}' || echo "")
        CURRENT_PORT=$(grep -A1 "^server:" "$CONFIG_DIR/config.yaml" | grep "port:" | awk '{print $2}' || echo "")
    fi

    # Set defaults
    local DEFAULT_OLLAMA_URL="${CURRENT_OLLAMA_URL:-http://localhost:11434}"
    local DEFAULT_OLLAMA_MODEL="${CURRENT_OLLAMA_MODEL:-llama3.1:8b}"
    local DEFAULT_PORT="${CURRENT_PORT:-8080}"

    # Prompt for values
    read -p "Ollama server URL [$DEFAULT_OLLAMA_URL]: " OLLAMA_URL
    OLLAMA_URL="${OLLAMA_URL:-$DEFAULT_OLLAMA_URL}"

    read -p "Ollama model [$DEFAULT_OLLAMA_MODEL]: " OLLAMA_MODEL
    OLLAMA_MODEL="${OLLAMA_MODEL:-$DEFAULT_OLLAMA_MODEL}"

    read -p "Server port [$DEFAULT_PORT]: " PORT
    PORT="${PORT:-$DEFAULT_PORT}"

    # Write config file
    cat > "$CONFIG_DIR/config.yaml" <<EOF
# Agent Gateway Configuration File
# Generated by install.sh

# Ollama server settings
ollama:
  url: $OLLAMA_URL
  model: $OLLAMA_MODEL

# HTTP server settings
server:
  port: $PORT

# Program execution settings
execution:
  timeout: 30s

# Programs directory (relative to gateway binary)
programs:
  directory: ./programs
EOF

    echo ""
    echo "✓ Config file created: $CONFIG_DIR/config.yaml"
    echo ""
}

# Setup configuration
setup_config

# Install Go dependencies
echo "Installing Go dependencies..."
cd "$SCRIPT_DIR"
go mod tidy
echo "✓ Dependencies installed"

# Build the gateway
echo "Building agent-gateway..."
go build -o "$BIN_DIR/agent-gateway" main.go config.go
echo "✓ Gateway built: $BIN_DIR/agent-gateway"

# Build programs
echo "Building programs..."
PROGRAMS_BUILT=0

for program_dir in "$SCRIPT_DIR/programs"/*; do
    if [ -d "$program_dir" ]; then
        program_name=$(basename "$program_dir")

        # Skip test programs that are already built
        if [ -f "$program_dir/$program_name" ]; then
            echo "  - $program_name (already built)"
            PROGRAMS_BUILT=$((PROGRAMS_BUILT + 1))
            continue
        fi

        # Check if there's a Go source file
        if ls "$program_dir"/*.go 1> /dev/null 2>&1; then
            echo "  - Building $program_name..."
            cd "$program_dir"
            go build -o "$program_name" *.go
            PROGRAMS_BUILT=$((PROGRAMS_BUILT + 1))
            cd "$SCRIPT_DIR"
        fi
    fi
done

echo "✓ Built $PROGRAMS_BUILT programs"

# Check if bin directory is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo "⚠️  WARNING: $BIN_DIR is not in your PATH"
    echo ""
    echo "Add this line to your ~/.bashrc or ~/.zshrc:"
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
    echo ""
fi

echo ""
echo "=== Installation Complete! ==="
echo ""
echo "Config file: $CONFIG_DIR/config.yaml"
echo "Binary location: $BIN_DIR/agent-gateway"
echo ""
echo "To start the gateway:"
echo "  agent-gateway --config $CONFIG_DIR/config.yaml"
echo ""
echo "Or with command-line overrides:"
echo "  agent-gateway --ollama-url http://your-ollama:11434 --ollama-model llama3.1:8b"
echo ""
