#!/usr/bin/env bash
# extract_wisdom.sh - Wisdom Extraction Module (Tier 2)
#
# MODULE: extract_wisdom
# NAME: Extract Wisdom
# CATEGORY: wisdom
# TIER: 2
# DESCRIPTION: Extracts insights, ideas, quotes, and lessons from content (Fabric-style)
# PARAM: input_file:path:Path to content file (article, transcript, etc.)
# PARAM: output_file:path:Path to save wisdom report (optional)

set -euo pipefail

# Source utilities from .bstag installation
BSTAG_HOME="${BSTAG_HOME:-$HOME/.bstag}"

source "$BSTAG_HOME/utilities/file.sh"
source "$BSTAG_HOME/utilities/log.sh"
source "$BSTAG_HOME/utilities/llm.sh"

# Module: extract_wisdom
# Extracts wisdom from content using Claude (Tier 2 - deep analysis)
module.extract_wisdom() {
    local input_file="${1:-}"
    local output_file="${2:-}"

    # Validation
    if [[ -z "$input_file" ]]; then
        echo "Error: Input file required" >&2
        echo "Usage: extract_wisdom.sh <input_file> [output_file]" >&2
        return 1
    fi

    if ! file.exists "$input_file"; then
        echo "Error: File not found: $input_file" >&2
        return 1
    fi

    # Set default output
    if [[ -z "$output_file" ]]; then
        output_file="${input_file}.wisdom.md"
    fi

    util.log.info "Extracting wisdom from: $input_file"
    util.log.info "Using: Tier 2 (Claude API - Paid)"

    # Read input
    local content
    content=$(file.read "$input_file")

    # Check content length
    local char_count
    char_count=$(echo -n "$content" | wc -c)
    util.log.info "Content size: $char_count characters"

    # Fabric-style wisdom extraction prompt
    local prompt="You are an expert at extracting insights and wisdom from content.

Analyze the following content and extract:

## SUMMARY
A concise summary in 20 words or less

## IDEAS
- Extract 5-10 of the best ideas (one sentence each, no more than 15 words)

## INSIGHTS
- Extract 5-10 profound insights (one sentence each)

## QUOTES
- Extract 5-10 most powerful quotes (with attribution if possible)

## HABITS
- Extract any recommended habits or practices mentioned

## FACTS
- Extract interesting facts or statistics mentioned

## REFERENCES
- List any books, articles, people, or resources mentioned

## RECOMMENDATIONS
- Based on this content, what are 3-5 actionable recommendations?

Format your response as clean markdown with clear sections.

Content to analyze:
---
$content
---"

    # Query Claude (Tier 2)
    util.log.info "Processing with Claude API (this may take 10-30 seconds)..."
    local wisdom
    wisdom=$(util.llm.query_big "$prompt" 4096)

    # Check if we got a response
    if [[ -z "$wisdom" ]] || [[ "$wisdom" == "Error:"* ]]; then
        echo "Error: Failed to extract wisdom" >&2
        echo "Response: $wisdom" >&2
        echo ""
        echo "Make sure CLAUDE_API_KEY is set in ~/.bstag/config/llm.conf" >&2
        return 1
    fi

    # Build complete output with metadata
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat > "$output_file" << EOF
# Wisdom Extraction

**Source**: $(basename "$input_file")
**Extracted**: $timestamp
**Method**: Tier 2 (Claude Sonnet 4.5)

---

$wisdom

---

*Generated by BATTLESTAG Wisdom Extraction Module (Tier 2)*
EOF

    util.log.info "✓ Wisdom report saved to: $output_file"

    # Show summary
    local output_lines
    output_lines=$(wc -l < "$output_file")

    echo ""
    echo "Summary:"
    echo "  Input:     $char_count characters"
    echo "  Output:    $output_lines lines"
    echo "  Saved to:  $output_file"
    echo "  Tier:      2 (Claude API)"
    echo "  Cost:      ~\$0.02-0.05"
    echo ""
    echo "✓ Done! View with: cat $output_file"
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    module.extract_wisdom "$@"
fi
