#!/usr/bin/env bash
# csv_insight.sh - CSV Intelligence Module
#
# MODULE: csv_insight
# NAME: CSV Intelligence
# CATEGORY: data
# DESCRIPTION: Analyzes CSV files and provides AI-powered insights
# PARAM: csv_file (required, string) - Path to CSV file to analyze
# PARAM: output_report (optional, string) - Path to output markdown report
#
# Demonstrates: Modules → Utilities → Primitives architecture

set -euo pipefail

# Source utilities from .bstag installation
BSTAG_HOME="${BSTAG_HOME:-$HOME/.bstag}"

source "$BSTAG_HOME/utilities/file.sh"
source "$BSTAG_HOME/utilities/data.sh"
source "$BSTAG_HOME/utilities/log.sh"
source "$BSTAG_HOME/utilities/llm.sh"

# Module: csv_insight
# Analyze CSV file and generate insights report
module.csv_insight() {
    local csv_file="${1:-}"
    local output_report="${2:-}"

    # Validation
    if [[ -z "$csv_file" ]]; then
        echo "Error: CSV file required" >&2
        echo "Usage: csv_insight.sh <csv_file> [output_report]" >&2
        return 1
    fi

    # Set default output if not provided
    if [[ -z "$output_report" ]]; then
        output_report="${csv_file}.insight.md"
    fi

    if ! file.exists "$csv_file"; then
        echo "Error: CSV file not found: $csv_file" >&2
        return 1
    fi

    util.log.info "Starting CSV analysis: $csv_file"

    # Gather statistics
    util.log.info "Gathering statistics..."
    local header row_count

    header=$(util.csv.header "$csv_file")
    row_count=$(util.csv.count "$csv_file")

    # Get sample data (first 5 rows)
    local sample
    sample=$(head -n 6 "$csv_file")  # Header + 5 rows

    # Get file statistics
    local file_size
    file_size=$(file.size "$csv_file")

    # Count columns
    local col_count
    col_count=$(echo "$header" | tr ',' '\n' | wc -l)

    util.log.info "Statistics gathered: $row_count rows, $col_count columns"

    # Create context for LLM
    local llm_prompt="Analyze this CSV data and provide insights.

CSV File: $csv_file
Rows: $row_count
Columns: $col_count
Size: $file_size bytes

Header:
$header

Sample Data (first 5 rows):
$sample

Please provide:
1. A brief description of what this data represents
2. Key observations about the data structure
3. Any patterns, trends, or anomalies you notice
4. Potential use cases or analysis suggestions

Keep the response concise and actionable."

    # Get LLM insights
    util.log.info "Requesting AI analysis..."
    local ai_insights
    ai_insights=$(util.llm.query "$llm_prompt" 1000 2>&1) || {
        util.log.warn "LLM analysis failed, generating report without AI insights"
        ai_insights="AI analysis unavailable (LLM endpoint not reachable)"
    }

    # Generate report
    util.log.info "Generating report..."

    local timestamp
    timestamp=$(sys.date)

    cat > "$output_report" <<EOF
# CSV Intelligence Report

**File**: $csv_file
**Generated**: $timestamp
**Tool**: BATTLESTAG CSV Insight Module

---

## Statistics

- **Rows**: $row_count
- **Columns**: $col_count
- **File Size**: $file_size bytes
- **Header**: $header

## Sample Data

\`\`\`csv
$sample
\`\`\`

## AI Insights

$ai_insights

---

*Generated by BATTLESTAG Capability Hierarchy*
*Modules → Utilities → Primitives*
EOF

    util.log.info "Report generated: $output_report"

    echo "✓ Analysis complete!"
    echo "✓ Report saved to: $output_report"
    echo ""
    echo "Statistics:"
    echo "  Rows:    $row_count"
    echo "  Columns: $col_count"
    echo "  Size:    $file_size bytes"
}

# Main execution
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ $# -lt 1 ]]; then
        echo "CSV Intelligence Module" >&2
        echo "" >&2
        echo "Usage: $0 <csv_file> [output_report]" >&2
        echo "" >&2
        echo "Analyzes CSV files and generates AI-powered insights." >&2
        echo "" >&2
        echo "Examples:" >&2
        echo "  $0 sales_data.csv" >&2
        echo "  $0 users.csv report.md" >&2
        exit 1
    fi

    module.csv_insight "$@"
fi
