#!/usr/bin/env bash
# review_code.sh - Code Review Module (Tier 1)
#
# MODULE: review_code
# NAME: Code Review (Basic)
# CATEGORY: code
# TIER: 1
# DESCRIPTION: Reviews code for bugs, security issues, and best practices using local LLM
# PARAM: code_file:path:Path to code file to review
# PARAM: output_file:path:Path to save review (optional)

set -euo pipefail

# Source utilities from .bstag installation
BSTAG_HOME="${BSTAG_HOME:-$HOME/.bstag}"

source "$BSTAG_HOME/utilities/file.sh"
source "$BSTAG_HOME/utilities/log.sh"
source "$BSTAG_HOME/utilities/llm.sh"

# Module: review_code
# Reviews code using local LLM (Tier 1 - fast, private)
module.review_code() {
    local code_file="${1:-}"
    local output_file="${2:-}"

    # Validation
    if [[ -z "$code_file" ]]; then
        echo "Error: Code file required" >&2
        echo "Usage: review_code.sh <code_file> [output_file]" >&2
        return 1
    fi

    if ! file.exists "$code_file"; then
        echo "Error: File not found: $code_file" >&2
        return 1
    fi

    # Set default output
    if [[ -z "$output_file" ]]; then
        output_file="${code_file}.review.md"
    fi

    util.log.info "Reviewing code: $code_file"
    util.log.info "Using: Tier 1 (Local LLM - Free)"

    # Read code
    local code_content
    code_content=$(file.read "$code_file")

    # Detect language from extension
    local file_ext="${code_file##*.}"
    local language="unknown"
    case "$file_ext" in
        sh|bash) language="Bash" ;;
        py) language="Python" ;;
        js) language="JavaScript" ;;
        ts) language="TypeScript" ;;
        go) language="Go" ;;
        rb) language="Ruby" ;;
        java) language="Java" ;;
        c|h) language="C" ;;
        cpp|cc|hpp) language="C++" ;;
        rs) language="Rust" ;;
        php) language="PHP" ;;
        *) language="$file_ext" ;;
    esac

    # Check code length
    local line_count
    line_count=$(echo "$code_content" | wc -l)
    util.log.info "File: $line_count lines of $language"

    # Tier 1 code review prompt (structured, checklist-based)
    local prompt="You are a senior software engineer reviewing code.

Review the following $language code and provide structured feedback on these areas:

1. BUGS & LOGIC ERRORS
   - Identify any logic errors or potential bugs
   - Check for off-by-one errors, null handling, edge cases

2. SECURITY ISSUES
   - Look for injection vulnerabilities (SQL, command, XSS)
   - Check input validation
   - Identify sensitive data exposure

3. PERFORMANCE PROBLEMS
   - Find inefficient algorithms or loops
   - Spot unnecessary computations
   - Identify memory leaks or excessive allocations

4. CODE QUALITY
   - Check readability and naming
   - Evaluate error handling
   - Assess code organization

5. BEST PRACTICES
   - Language-specific idioms
   - Common patterns and anti-patterns

Format your response as:

## Summary
[One paragraph overall assessment]

## Issues Found
[For each issue:]
- **[Severity: Critical/High/Medium/Low]** Category: Issue
  - Line(s): [line numbers if identifiable]
  - Problem: [description]
  - Suggestion: [how to fix]

## Positive Aspects
[What the code does well]

Code to review:
\`\`\`$language
$code_content
\`\`\`"

    # Query local LLM (Tier 1)
    util.log.info "Analyzing code with local LLM..."
    local review
    review=$(util.llm.query_small "$prompt" 3000)

    # Check if we got a response
    if [[ -z "$review" ]] || [[ "$review" == "Error:"* ]]; then
        echo "Error: Failed to review code" >&2
        echo "Response: $review" >&2
        return 1
    fi

    # Build complete output with metadata
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat > "$output_file" << EOF
# Code Review Report

**File**: $(basename "$code_file")
**Language**: $language
**Lines**: $line_count
**Reviewed**: $timestamp
**Method**: Tier 1 (Local LLM - Basic Review)

---

$review

---

## Next Steps

1. Address **Critical** and **High** severity issues first
2. Consider **Medium** issues for code quality
3. **Low** issues are nice-to-haves
4. For complex issues, consider Tier 2 review (advanced analysis)

---

*Generated by BATTLESTAG Code Review Module (Tier 1)*
*Cost: \$0.00 | Privacy: 100% Local*
EOF

    util.log.info "✓ Review saved to: $output_file"

    # Show summary
    local issue_count
    issue_count=$(grep -c "^\*\*\[Severity:" "$output_file" 2>/dev/null || echo "0")

    echo ""
    echo "Summary:"
    echo "  File:      $(basename "$code_file")"
    echo "  Language:  $language"
    echo "  Lines:     $line_count"
    echo "  Issues:    $issue_count found"
    echo "  Saved to:  $output_file"
    echo "  Tier:      1 (Local LLM)"
    echo "  Cost:      \$0.00"
    echo ""
    echo "✓ Done! View with: cat $output_file"
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    module.review_code "$@"
fi
